-- 여행
DROP TABLE IF EXISTS trip RESTRICT;

-- 유저
DROP TABLE IF EXISTS user RESTRICT;

-- 쪽지
DROP TABLE IF EXISTS letter RESTRICT;

-- 댓글
DROP TABLE IF EXISTS comment RESTRICT;

-- 여행지유형대분류
DROP TABLE IF EXISTS firstclass RESTRICT;

-- 여행지정보
DROP TABLE IF EXISTS location RESTRICT;

-- SNS
DROP TABLE IF EXISTS sns RESTRICT;

-- 즐겨찾기
DROP TABLE IF EXISTS favor RESTRICT;

-- 좋아요
DROP TABLE IF EXISTS boardlike RESTRICT;

-- 여행이미지
DROP TABLE IF EXISTS tripimg RESTRICT;

-- 게시판
DROP TABLE IF EXISTS board RESTRICT;

-- 차단
DROP TABLE IF EXISTS ben RESTRICT;

-- 시도
DROP TABLE IF EXISTS city RESTRICT;

-- 시군구
DROP TABLE IF EXISTS state RESTRICT;

-- 여행테마
DROP TABLE IF EXISTS thema RESTRICT;

-- 여행일정
DROP TABLE IF EXISTS schedule RESTRICT;

-- 여행지유형중분류
DROP TABLE IF EXISTS secondclass RESTRICT;

-- 여행지유형소분류
DROP TABLE IF EXISTS thirdclass RESTRICT;

-- 차단분류
DROP TABLE IF EXISTS bentype RESTRICT;

-- 이미지첨부
DROP TABLE IF EXISTS attachedimage RESTRICT;

-- 게시글분류
DROP TABLE IF EXISTS boardtype RESTRICT;

-- 동행
DROP TABLE IF EXISTS companion RESTRICT;-- 여행
DROP TABLE IF EXISTS trip RESTRICT;

-- 유저
DROP TABLE IF EXISTS user RESTRICT;

-- 쪽지
DROP TABLE IF EXISTS letter RESTRICT;

-- 댓글
DROP TABLE IF EXISTS comment RESTRICT;

-- 여행지유형대분류
DROP TABLE IF EXISTS firstclass RESTRICT;

-- 여행지정보
DROP TABLE IF EXISTS location RESTRICT;

-- SNS
DROP TABLE IF EXISTS sns RESTRICT;

-- 즐겨찾기
DROP TABLE IF EXISTS favor RESTRICT;

-- 좋아요
DROP TABLE IF EXISTS boardlike RESTRICT;

-- 여행이미지
DROP TABLE IF EXISTS tripimg RESTRICT;

-- 게시판
DROP TABLE IF EXISTS board RESTRICT;

-- 차단
DROP TABLE IF EXISTS ben RESTRICT;

-- 시도
DROP TABLE IF EXISTS city RESTRICT;

-- 시군구
DROP TABLE IF EXISTS state RESTRICT;

-- 여행테마
DROP TABLE IF EXISTS thema RESTRICT;

-- 여행일정
DROP TABLE IF EXISTS schedule RESTRICT;

-- 여행지유형중분류
DROP TABLE IF EXISTS secondclass RESTRICT;

-- 여행지유형소분류
DROP TABLE IF EXISTS thirdclass RESTRICT;

-- 차단분류
DROP TABLE IF EXISTS bentype RESTRICT;

-- 이미지첨부
DROP TABLE IF EXISTS attachedimage RESTRICT;

-- 게시글분류
DROP TABLE IF EXISTS boardtype RESTRICT;

-- 동행
DROP TABLE IF EXISTS companion RESTRICT;-- 여행
DROP TABLE IF EXISTS trip RESTRICT;

-- 유저
DROP TABLE IF EXISTS user RESTRICT;

-- 쪽지
DROP TABLE IF EXISTS letter RESTRICT;

-- 댓글
DROP TABLE IF EXISTS comment RESTRICT;

-- 여행지유형대분류
DROP TABLE IF EXISTS firstclass RESTRICT;

-- 여행지정보
DROP TABLE IF EXISTS location RESTRICT;

-- SNS
DROP TABLE IF EXISTS sns RESTRICT;

-- 즐겨찾기
DROP TABLE IF EXISTS favor RESTRICT;

-- 좋아요
DROP TABLE IF EXISTS boardlike RESTRICT;

-- 여행이미지
DROP TABLE IF EXISTS tripimg RESTRICT;

-- 게시판
DROP TABLE IF EXISTS board RESTRICT;

-- 차단
DROP TABLE IF EXISTS ben RESTRICT;

-- 시도
DROP TABLE IF EXISTS city RESTRICT;

-- 시군구
DROP TABLE IF EXISTS state RESTRICT;

-- 여행테마
DROP TABLE IF EXISTS thema RESTRICT;

-- 여행일정
DROP TABLE IF EXISTS schedule RESTRICT;

-- 여행지유형중분류
DROP TABLE IF EXISTS secondclass RESTRICT;

-- 여행지유형소분류
DROP TABLE IF EXISTS thirdclass RESTRICT;

-- 차단분류
DROP TABLE IF EXISTS bentype RESTRICT;

-- 이미지첨부
DROP TABLE IF EXISTS attachedimage RESTRICT;

-- 게시글분류
DROP TABLE IF EXISTS boardtype RESTRICT;

-- 동행
DROP TABLE IF EXISTS companion RESTRICT;-- 여행
DROP TABLE IF EXISTS trip RESTRICT;

-- 유저
DROP TABLE IF EXISTS user RESTRICT;

-- 쪽지
DROP TABLE IF EXISTS letter RESTRICT;

-- 댓글
DROP TABLE IF EXISTS comment RESTRICT;

-- 여행지유형대분류
DROP TABLE IF EXISTS firstclass RESTRICT;

-- 여행지정보
DROP TABLE IF EXISTS location RESTRICT;

-- SNS
DROP TABLE IF EXISTS sns RESTRICT;

-- 즐겨찾기
DROP TABLE IF EXISTS favor RESTRICT;

-- 좋아요
DROP TABLE IF EXISTS boardlike RESTRICT;

-- 여행이미지
DROP TABLE IF EXISTS tripimg RESTRICT;

-- 게시판
DROP TABLE IF EXISTS board RESTRICT;

-- 차단
DROP TABLE IF EXISTS ben RESTRICT;

-- 시도
DROP TABLE IF EXISTS city RESTRICT;

-- 시군구
DROP TABLE IF EXISTS state RESTRICT;

-- 여행테마
DROP TABLE IF EXISTS thema RESTRICT;

-- 여행일정
DROP TABLE IF EXISTS schedule RESTRICT;

-- 여행지유형중분류
DROP TABLE IF EXISTS secondclass RESTRICT;

-- 여행지유형소분류
DROP TABLE IF EXISTS thirdclass RESTRICT;

-- 차단분류
DROP TABLE IF EXISTS bentype RESTRICT;

-- 이미지첨부
DROP TABLE IF EXISTS attachedimage RESTRICT;

-- 게시글분류
DROP TABLE IF EXISTS boardtype RESTRICT;

-- 동행
DROP TABLE IF EXISTS companion RESTRICT;-- 여행
DROP TABLE IF EXISTS trip RESTRICT;

-- 유저
DROP TABLE IF EXISTS user RESTRICT;

-- 쪽지
DROP TABLE IF EXISTS letter RESTRICT;

-- 댓글
DROP TABLE IF EXISTS comment RESTRICT;

-- 여행지유형대분류
DROP TABLE IF EXISTS firstclass RESTRICT;

-- 여행지정보
DROP TABLE IF EXISTS location RESTRICT;

-- SNS
DROP TABLE IF EXISTS sns RESTRICT;

-- 즐겨찾기
DROP TABLE IF EXISTS favor RESTRICT;

-- 좋아요
DROP TABLE IF EXISTS boardlike RESTRICT;

-- 여행이미지
DROP TABLE IF EXISTS tripimg RESTRICT;

-- 게시판
DROP TABLE IF EXISTS board RESTRICT;

-- 차단
DROP TABLE IF EXISTS ben RESTRICT;

-- 시도
DROP TABLE IF EXISTS city RESTRICT;

-- 시군구
DROP TABLE IF EXISTS state RESTRICT;

-- 여행테마
DROP TABLE IF EXISTS thema RESTRICT;

-- 여행일정
DROP TABLE IF EXISTS schedule RESTRICT;

-- 여행지유형중분류
DROP TABLE IF EXISTS secondclass RESTRICT;

-- 여행지유형소분류
DROP TABLE IF EXISTS thirdclass RESTRICT;

-- 차단분류
DROP TABLE IF EXISTS bentype RESTRICT;

-- 이미지첨부
DROP TABLE IF EXISTS attachedimage RESTRICT;

-- 게시글분류
DROP TABLE IF EXISTS boardtype RESTRICT;

-- 동행
DROP TABLE IF EXISTS companion RESTRICT;
