/*
 * This source file was generated by the Gradle 'init' task
 */
package project.tripMaker;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        ServerApp classUnderTest = new ServerApp();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
